#!/usr/bin/env python3
import argparse
import json
import sys


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, help="JSONL file generated by generate_11n_dataset.py in 4n mode")
    args = ap.parse_args()

    with open(args.input, "r", encoding="utf-8") as f:
        rows = [json.loads(line) for line in f if line.strip()]

    if not rows:
        print("ERROR: no records in output")
        return 1

    for idx, row in enumerate(rows, start=1):
        candidates = row.get("candidates")
        if not isinstance(candidates, list) or len(candidates) != 4:
            print(f"ERROR: record {idx} candidates length != 4")
            return 1
        if "variant_type" not in row:
            print(f"ERROR: record {idx} missing variant_type")
            return 1
        if not (row.get("problem_id") or row.get("task_id") or row.get("name")):
            print(f"ERROR: record {idx} missing problem id field")
            return 1

    print(f"OK: validated {len(rows)} records")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
