import argparse
import json
import sys
from pathlib import Path

def main() -> int:
    ap = argparse.ArgumentParser(description="Validate 4N simulation output schema")
    ap.add_argument("--input", required=True, help="JSONL file generated by generate_11n_dataset.py --mode 4n")
    args = ap.parse_args()

    path = Path(args.input)
    if not path.is_file():
        print(f"[ERROR] input not found: {path}")
        print("ALL_CHECKS_PASS=0")
        return 1

    errors = []
    with path.open("r", encoding="utf-8") as f:
        for idx, line in enumerate(f, start=1):
            if not line.strip():
                continue
            try:
                item = json.loads(line)
            except Exception as e:
                errors.append(f"line {idx}: invalid json ({e})")
                continue

            candidates = item.get("candidates", [])
            if len(candidates) != 4:
                errors.append(f"line {idx}: candidates length {len(candidates)} != 4")
            if "variant_type" not in item:
                errors.append(f"line {idx}: missing variant_type")
            if not (item.get("name") or item.get("task_id") or item.get("problem_id")):
                errors.append(f"line {idx}: missing problem id field (name/task_id/problem_id)")

    if errors:
        print("ALL_CHECKS_PASS=0")
        for e in errors:
            print(f"[ERROR] {e}")
        return 1

    print("ALL_CHECKS_PASS=1")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
